name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Test
        run: uv run --group dev pytest

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Build
        run: uv build

      - name: Publish to GitHub Packages
        run: |
          uv publish \
            --publish-url https://python.pkg.github.com/${{ github.repository_owner }}/ \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }}
